import Head from 'next/head'

import styles from '../styles/Home.module.css'
import React, {useState} from 'react'

export default function Home() {




const [std_inp, setstd_inp] = useState('');
const [std_img, setstd_img] = useState([]);



const Slctud = async () =>{

  const punto_accso = 'https://api.unsplash.com/search/photos'
const query_api = std_inp
const client_id = 'xDSfXnprz2CsHIdm_M8p8KsuAUKAz3BE5xGNIl4ZW_M'

const res = await fetch(`${punto_accso}?query=${std_inp}&page=1&per_page=4&client_id=${client_id}`)
const data = await res.json()
setstd_img(data.results)

}




  return (
   <>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<header>
Test
</header>
<div className={styles.d_imgs}>

{
std_img.map(itm =>{

return <div className={styles.d_qry_imgs00} key={itm.id}>
<div className={'d_qry_imgs01'}></div>

<div>
  
</div>

<style jsx>{`
.d_qry_imgs01{
  width:18vw;
  height:17.5rem;
  background:rgb(228, 232, 238);
background-size: cover;
background-image:url(${itm.urls.regular});
border-radius: 0.3rem 0.3rem 0.3rem 0.3rem;
box-shadow: 0rem 0rem 0.2rem 0.2rem rgb(188, 206, 211) ;
}

@media only screen and (max-width:426px){
  .d_qry_imgs01{
    width:78vw;
    height:9rem;
  }

}


`}</style>


</div>


})}



</div>

<div className={styles.d_busqueda}>
<input

value={std_inp} onChange={(e)=>{

  setstd_inp(e.currentTarget.value)

}}></input>

<button onClick={()=>{

Slctud()


}}>Buscar</button>
</div>

<footer></footer>


     </>
     
  )


  
}



